### ISSUE TITLE
Installation script fails on ubuntu

### ISSUE THREAD

**Issue by endrec** [datawire/blackbird#21]
A `sudo` is missing in line 68

**Comment by richarddli** [comment]
Thank you for the fix! Were you able to get the rest of Blackbird working? Would love your feedback.

**Comment by endrec** [comment]
Just finished the installation of the reference project, no other issues so far. :) 
I stumbled upon an article mentioning ambassador two days ago, and I'm currently researching api gateway options for our next project, it happened to be the right time. As the documentation looked promising, I decided to give it a go, and as you seems to solve a lot of my daily problems with the rest of the blackbird project, I decided to try them out, and possibly use your toolset from now on.
Good work, keep it up. :)
